name: Deploy to VPS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v4

        -   name: Set up SSH
            uses: webfactory/ssh-agent@v0.8.0
            with:
                ssh-private-key: ${{ secrets.VPS_SSH }}

        -   name: Deploy using SCP
            run: scp -r -P ${{ secrets.VPS_PORT }} ./* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/nemanja-tomic.de